name = "hyperbuoy"
type = "javascript"
account_id = "824930968003748fd33c2ec0cc64bd3b"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
    {binding = "BUCKET", id = "dada046b8ccc474c856c4f9025b52f80", preview_id = "dada046b8ccc474c856c4f9025b52f80"}
]